enum PlaceField {
  address('ADDRESS'),
  addressComponents('ADDRESS_COMPONENTS'),
  businessStatus('BUSINESS_STATUS'),
  curbsidePickup('CURBSIDE_PICKUP'),
  currentOpeningHours('CURRENT_OPENING_HOURS'),
  delivery('DELIVERY'),
  dineIn('DINE_IN'),
  editorialSummary('EDITORIAL_SUMMARY'),
  iconBackgroundColor('ICON_BACKGROUND_COLOR'),
  iconUrl('ICON_URL'),
  id('ID'),
  latLng('LAT_LNG'),
  name('NAME'),
  openingHours('OPENING_HOURS'),
  phoneNumber('PHONE_NUMBER'),
  photoMetadatas('PHOTO_METADATAS'),
  plusCode('PLUS_CODE'),
  priceLevel('PRICE_LEVEL'),
  rating('RATING'),
  reservable('RESERVABLE'),
  secondaryOpeningHours('SECONDARY_OPENING_HOURS'),
  servesBeer('SERVES_BEER'),
  servesBreakfast('SERVES_BREAKFAST'),
  servesBrunch('SERVES_BRUNCH'),
  servesDinner('SERVES_DINNER'),
  servesLunch('SERVES_LUNCH'),
  servesVegetarianFood('SERVES_VEGETARIAN_FOOD'),
  servesWine('SERVES_WINE'),
  takeout('TAKEOUT'),
  types('TYPES'),
  userRatingsTotal('USER_RATINGS_TOTAL'),
  utcOffset('UTC_OFFSET'),
  viewport('VIEWPORT'),
  websiteUri('WEBSITE_URI'),
  wheelchairAccessibleEntrance('WHEELCHAIR_ACCESSIBLE_ENTRANCE');

  const PlaceField(this.label);

  final String label;
}
